# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        #MainWindow.resize(800,600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainmenu = QtWidgets.QWidget()
        self.mainmenu.setObjectName("mainmenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainmenu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.mainmenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.toQuestion = QtWidgets.QPushButton(self.mainmenu)
        font = QtGui.QFont()
        font.setFamily("Serif")
        self.toQuestion.setFont(font)
        self.toQuestion.setObjectName("toQuestion")
        self.horizontalLayout_3.addWidget(self.toQuestion)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.toSettings = QtWidgets.QPushButton(self.mainmenu)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setUnderline(False)
        self.toSettings.setFont(font)
        self.toSettings.setObjectName("toSettings")
        self.horizontalLayout_2.addWidget(self.toSettings)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.mainmenu)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.mainmenu)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.label_4 = QtWidgets.QLabel(self.settings)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.topicbox = QtWidgets.QComboBox(self.settings)
        self.topicbox.setObjectName("topicbox")
        self.horizontalLayout_5.addWidget(self.topicbox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.label_5 = QtWidgets.QLabel(self.settings)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.difficultybox = QtWidgets.QComboBox(self.settings)
        self.difficultybox.setObjectName("difficultybox")
        self.horizontalLayout_8.addWidget(self.difficultybox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.toMainMenu = QtWidgets.QPushButton(self.settings)
        self.toMainMenu.setObjectName("toMainMenu")
        self.horizontalLayout_4.addWidget(self.toMainMenu)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.settings)
        self.question = QtWidgets.QWidget()
        self.question.setObjectName("question")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.question)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        #spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        #self.verticalLayout_5.addItem(spacerItem11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum) # changed from minium
        self.horizontalLayout.addItem(spacerItem12)
        self.toAnswer = QtWidgets.QPushButton(self.question)
        self.toAnswer.setObjectName("toAnswer")
        self.horizontalLayout.addWidget(self.toAnswer)
        self.toMainMenu_2 = QtWidgets.QPushButton(self.question)
        self.toMainMenu_2.setObjectName("toMainMenu_2")
        self.horizontalLayout.addWidget(self.toMainMenu_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.question)
        self.answer = QtWidgets.QWidget()
        self.answer.setObjectName("answer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.answer)
        self.verticalLayout.setObjectName("verticalLayout")
        #spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        #self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.toQuestion_2 = QtWidgets.QPushButton(self.answer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toQuestion_2.sizePolicy().hasHeightForWidth())
        self.toQuestion_2.setSizePolicy(sizePolicy)
        self.toQuestion_2.setObjectName("toQuestion_2")
        self.horizontalLayout_6.addWidget(self.toQuestion_2)
        self.toMainMenu_3 = QtWidgets.QPushButton(self.answer)
        self.toMainMenu_3.setObjectName("toMainMenu_3")
        self.horizontalLayout_6.addWidget(self.toMainMenu_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.answer)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum))
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Mathematica Problem Generator"))
        self.toQuestion.setText(_translate("MainWindow", "Generate a Question"))
        self.toSettings.setText(_translate("MainWindow", "Settings"))
        self.label_2.setText(_translate("MainWindow", "Made by Sai kumar Murali krishnan."))
        self.label_3.setText(_translate("MainWindow", "Settings"))
        self.label_4.setText(_translate("MainWindow", "Topic:"))
        self.label_5.setText(_translate("MainWindow", "Difficulty:"))
        self.toMainMenu.setText(_translate("MainWindow", "Main Menu"))
        self.toAnswer.setText(_translate("MainWindow", "Answer"))
        self.toMainMenu_2.setText(_translate("MainWindow", "Main Menu"))
        self.toQuestion_2.setText(_translate("MainWindow", "New Question"))
        self.toMainMenu_3.setText(_translate("MainWindow", "Main Menu"))


